// CmnBase.h

#ifndef __CmnBase_h__
#define __CmnBase_h__

typedef size_t VHWND;

#define CMN_OK			    0
#define CMN_NOTOK		   -1

#define CMN_HANDSHAKE_1		1
#define CMN_HANDSHAKE_2		2
#define CMN_SWITCH_FORM		3

//SendString Defines
#define CMN_SENDSTR_INITIALIZE   100      //lParam: strlen(str_to_send)
#define CMN_SENDSTR_FINALIZE     101      //lParam: strlen(str_to_send)
#define CMN_SENDSTR_SENDING      102      //lParam: (index)16 + (str[index])16 = unsigned
#define CMN_SELECTION_END		 103

//Viewpoint Actions
#define CMN_VIEWPOINT_ACTIONS	1000
#define CMN_SELECT				(CMN_VIEWPOINT_ACTIONS + 1)
#define CMN_EXTRUDE_CURV		(CMN_VIEWPOINT_ACTIONS + 2)
#define CMN_RECORD_POINT		(CMN_VIEWPOINT_ACTIONS + 3)
#define CMN_RECORD_VECTOR		(CMN_VIEWPOINT_ACTIONS + 4)
#define CMN_RECORD_SCALER		(CMN_VIEWPOINT_ACTIONS + 5)
#define CMN_ROTATE_MODELS		(CMN_VIEWPOINT_ACTIONS + 6)
#define CMN_TRANSLATE_MODELS	(CMN_VIEWPOINT_ACTIONS + 7)
#define CMN_SCALE_MODELS		(CMN_VIEWPOINT_ACTIONS +8)
#define CMN_MIRROR_MODELS		(CMN_VIEWPOINT_ACTIONS +9)
#define CMN_GET_MARGINS			(CMN_VIEWPOINT_ACTIONS +10)
#define CMN_SET_SELECTED		(CMN_VIEWPOINT_ACTIONS +11)
#define CMN_OPEN_FILE			(CMN_VIEWPOINT_ACTIONS +12)
#define CMN_ADD_SEQLINES		(CMN_VIEWPOINT_ACTIONS +13)
#define CMN_SELECTION_OK		(CMN_VIEWPOINT_ACTIONS +14)
#define CMN_SELECTION_ABORT		(CMN_VIEWPOINT_ACTIONS +15)
#define CMN_SETVISIBLE			(CMN_VIEWPOINT_ACTIONS +16)

//Returns from Viewpoint Actions
#define CMN_VIEWPOINT_RETURNS	10000
#define CMN_SEND_OK				(CMN_VIEWPOINT_RETURNS + 1)
#define CMN_SEND_CANCEL			(CMN_VIEWPOINT_RETURNS + 2)

//Karel Kalýp Imalat DLL Operations
#define CMN_KKI_OPERATIONS		11000
#define CMN_KKI_SETNUMPARAM		(CMN_KKI_OPERATIONS + 1)
#define CMN_KKI_SETOPTPARAM		(CMN_KKI_OPERATIONS + 2)
#define CMN_KKI_CALCULATE		(CMN_KKI_OPERATIONS + 3)
#define CMN_KKI_MAKEMACHSURF	(CMN_KKI_OPERATIONS + 4)
#define CMN_KKI_GETTOOLNAMES	(CMN_KKI_OPERATIONS + 5)
#define CMN_KKI_SETSELTOOL		(CMN_KKI_OPERATIONS + 6)
#define CMN_KKI_SETSELMACHSURF	(CMN_KKI_OPERATIONS + 7)
#define CMN_KKI_SETMACHSTRATEGY (CMN_KKI_OPERATIONS + 8)
#define CMN_KKI_GETMACHSURFS	(CMN_KKI_OPERATIONS + 9)
#define CMN_KKI_GETTOOLDIAM		(CMN_KKI_OPERATIONS + 10)
#define CMN_KKI_SETLEADLINKSET  (CMN_KKI_OPERATIONS + 11)
#define CMN_KKI_MAKEMACHCURV	(CMN_KKI_OPERATIONS + 12)
#define CMN_KKI_GETMACHCURVS	(CMN_KKI_OPERATIONS + 13)
#define CMN_KKI_SETSELMACHCURV	(CMN_KKI_OPERATIONS + 14)
#define CMN_KKI_SETOPNAME		(CMN_KKI_OPERATIONS + 15)
#define CMN_KKI_SETROUGHINGSTOCK (CMN_KKI_OPERATIONS + 16)
#define CMN_KKI_RUNCUTSIM (CMN_KKI_OPERATIONS + 17)
#define CMN_KKI_GETOPERATIONNAMES (CMN_KKI_OPERATIONS + 18)
#define CMN_KKI_POSTOPERATIONS (CMN_KKI_OPERATIONS + 19)
#define CMN_KKI_GETMACHSURFSMARGINS (CMN_KKI_OPERATIONS + 20)
#define CMN_KKI_GETUISTRINGS (CMN_KKI_OPERATIONS + 21)
#define CMN_KKI_GETLISTRINGS (CMN_KKI_OPERATIONS + 22)
#define CMN_KKI_GETSELMACHSURFS (CMN_KKI_OPERATIONS + 23)
#define CMN_KKI_GETSELMACHCURVS (CMN_KKI_OPERATIONS + 24)
#define CMN_KKI_GETLEADINOUTS (CMN_KKI_OPERATIONS + 25)
#define CMN_KKI_ADDTOOL (CMN_KKI_OPERATIONS + 26)
#define CMN_KKI_GETTOOLPARAM (CMN_KKI_OPERATIONS + 27)
#define CMN_KKI_DELETETOOL (CMN_KKI_OPERATIONS + 28)
#define CMN_KKI_RECALCULATEFORILKOTEK (CMN_KKI_OPERATIONS + 29)
// Geo DLL functions
#define CMN_GEO_OPERATIONS 12000
#define  CMN_GEO_MAKEENCBOX	(CMN_GEO_OPERATIONS + 1)
#define CMN_GEO_MAKEENCBOX2 (CMN_GEO_OPERATIONS + 2)

#define CMN_ALUKES_OPERATIONS 14000
#define CMN_ALUKES_SEND (CMN_ALUKES_OPERATIONS + 1)
#define CMN_ALUKES_RECIEVE (CMN_ALUKES_OPERATIONS + 2)
// Generic
#define CMN_GENERIC 16000
#define CMN_CALLBACK_SOLIDCNCKEYVALPAIR (CMN_GENERIC + 1)
#define CMN_COMMANDFROMNET (CMN_GENERIC + 2)
// AnyShape
#define CMN_ANYSHAPE_OPERATIONS 17000
#define CMN_SENDTOANYSHAPE (CMN_ANYSHAPE_OPERATIONS + 1)
#define CMN_COMMANDFROMANYSHAPE (CMN_ANYSHAPE_OPERATIONS + 2) 
// AnyShape
// CutBlocks
#define CMN_CUTBLOCKS_OPERATIONS 18000
#define CMN_SENDTOCUTBLOCKS (CMN_CUTBLOCKS_OPERATIONS + 1)
#define CMN_COMMANDFROMCUTBLOCKS (CMN_CUTBLOCKS_OPERATIONS + 2)
// CutBlocks
// ViewPoint
#define CMN_VIEWPOINT_OPERATIONS 19000
#define CMN_COMMANDFROMVIEWPOINT (CMN_VIEWPOINT_OPERATIONS +1)
#define CMN_ADDOPERATIONTOALUKES (CMN_VIEWPOINT_OPERATIONS +2)
//ViewPoint
#define CMN_SETSEPARATOR ';'

class CmnBase
{
public:
	int SendString(const TCHAR *str);
	int SendStringToVp (const TCHAR *str);
protected:
	//CmnBase (UINT uniqmsg,HWND recieverHWND);
	/*static*/ VHWND m_activeDllHWND;
	/*static*/ VHWND m_viewPointHWND;
public:
	//CmnBase();
	CmnBase (VHWND viewPointHWND);
	int SendMessageToVp (const std::vector<VStr> &msgVec);// vector is a key-value pair list , it should have even number of elements , first key-value pair must be like "Command"-"SendOperationToAluKes" , second like "OperationName"-"op1"
	/*static*/ VHWND GetViewPointHWnd ();
	/*static*/ void SetViewPointHWnd(VHWND viewPointHWnd);
protected:
	int SendKeyValuePairs (const std::map<VStr,VStr> &keyValueMap);
public:	
	int SendKeyValuePairsAndInvokeApplicationRegisteredCallbackFunction (const std::map<VStr,VStr> &keyValueMap);
public:
	const static UINT InterAppMsg;
	void SendStringByASIO(const char* str);
};

#endif